name: "Auto Assign Reviewers"
on:
  pull_request_target:
    types: [opened, ready_for_review, synchronize]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Список всех возможных ревьюверов
          reviewers: |
            YuriSilenok
          numberOfReviewers: 1
